name: doctor_appointment_manager
description: "A Flutter application for managing doctor appointments."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Firebase packages
  firebase_core: ^3.14.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.9
  firebase_storage: 12.4.7  # إضافة مكتبة تخزين الصور
  # State management
  provider: ^6.1.1
  # UI enhancements
  flutter_spinkit: ^5.2.0
  intl: ^0.19.0
  fluttertoast: ^8.2.4
  image_picker: ^1.0.7  # إضافة مكتبة اختيار الصور

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/images/
  #   - assets/icons/
